
[datalink]
# datalink host, defaults to localhost
host='localhost'
# datalink port, defaults to 18000
port=16008
# Match regular expression pattern on stream ids, ex '.*/JSON'
match='FDSN:.*/(BZ)?JSON'

[jsonl]
# JSONL Write pattern, usage similar to MSeedWrite in ringserver
write='/data/scsn/www/magcalcjsonl/%n/%s/%Y/%j/%n.%s.%l.%c.%Y.%j.%H.jsonl'
